/**
 * The Friends' words. One big well that friend.ts draws from, so lines can be added without touching the logic:
 *   VOICES    what each family says to the things that happen (region, creature, grave, fight, rare find…)
 *   SKILLS    what each family says while working a skill (chopping, fishing, smithing, brewing, praying…)
 *   CHATTER   random talk: a line now and then for no reason, in each family's manner, plus the odd shared one
 * Families: 0 Skeleton, 1 Mask, 2 Family, 3 Cellular, 4 Asymmetry, 5 Hoverer, 6 Colossus, 7 Sparkling, 8 Hollow.
 * {name} is a named thing, {n} a count, {skill} a skill's name, {region} where you are, {friend} your Friend's name.
 * A creature's name is never after "a" (it may start with a vowel). Every line is translated (lang/friend.ts), so the
 * jokes are in what's said, not in English wordplay.
 */
import type { Skill } from "./data.ts";

export type FriendEvent =
  | "region" | "revisit" | "night" | "rain" | "creature" | "creature_again" | "dragon" | "dragon_again" | "undead" | "grave" | "altar" | "statue"
  | "fight" | "hurt" | "rare" | "quest" | "boss" | "death" | "mount" | "fellowship" | "mastery" | "tired" | "mine" | "chop" | "bones" | "underground" | "mountain" | "sea" | "hollow"
  | "mixture" | "outfit" | "friend_near" | "idle" | "levelup" | "full_pack" | "coins" | "shop" | "bank" | "pet" | "storm" | "fog" | "dawn" | "snow" | "lava" | "swamp" | "desert" | "village" | "ruin" | "water";
export type Voice = Partial<Record<FriendEvent, readonly string[]>>;

export const VOICES: readonly Voice[] = [
  // ---------- 0 Skeleton: deadpan, morbid, fond of you underneath ----------
  {
    region: ["{name}. I give it a century.", "{name}. Quiet. I like quiet.", "{name}. Plenty of room to lie down.", "{name}. Somebody's buried here. Somebody's always buried here."],
    revisit: ["{name} again. It hasn't aged a day. Neither have I.", "Back in {name}. The graves haven't moved."],
    night: ["Night. Nobody can tell what I am.", "Dark at last. I blend in."],
    rain: ["Rain. It goes straight through me.", "Rain. Nothing on me to soak. I've checked."],
    storm: ["Thunder. I felt that in all my bones. That's all of me.", "Lightning. For a moment everyone looks like me."],
    fog: ["Fog. Now we're all ghosts."],
    dawn: ["Morning. The living get up. I never lay down."],
    snow: ["Snow. I finally match something."],
    creature: ["That {name} has a skeleton too. Lucky thing.", "That {name} is all meat. Shame.", "That {name} is looking at my ribs like they're dinner."],
    creature_again: ["{name} number {n}. I've started a collection.", "Another {name}. I know its bones by heart."],
    dragon: ["A dragon. That's a lot of skeleton under there.", "Dragon. Imagine the size of its skull in a museum."],
    dragon_again: ["Another dragon. I'd like its jaw for the hallway.", "Dragon again. They never learn. Neither do we."],
    undead: ["Ugh. Amateurs.", "They give the rest of us a bad name.", "Let the dead rest. Present company excepted."],
    grave: ["Someone's resting. Lucky them.", "A grave. Wipe your feet."],
    altar: ["An altar. Bring bones. Not mine.", "They leave bones here. I try not to take it personally."],
    statue: ["The Old Friend. He's aged better than I have.", "Nice beard. I had hair once. Allegedly."],
    fight: ["Mind the ribs. I'm attached to them.", "Swing first. Apologise never.", "Go on. I'll hold your coat."],
    hurt: ["That'll scar. You, not me.", "Careful. You've still got blood to lose.", "Ow. On your behalf."],
    rare: ["Shiny. Have it buried with us.", "Treasure. We can't take it with us. I've asked."],
    quest: ["Done. Nobody died. Well. Nobody new.", "Finished. They'll carve that on a stone one day."],
    boss: ["Down. Lying down suits everyone.", "That was big. Now it's bones. Welcome to the club."],
    death: ["Well. Now you know how I feel.", "Dead. It's not so bad. Trust me."],
    mount: ["Four legs. More bones than me. Show-off.", "Gently. I rattle at a gallop."],
    fellowship: ["A fellowship. More people to outlive.", "Company. Someone to pick up my bits if I drop them."],
    mastery: ["Ninety-nine. They'll carve it on our stone.", "Ninety-nine. Worth staying up for. I always stay up."],
    levelup: ["A level. You're growing. I'm not.", "Up a level. Good. One of us should improve."],
    tired: ["Out of breath? I can't relate.", "Walk, then. I'm in no hurry. I've got forever."],
    mine: ["Stone. The second hardest thing I know.", "Dig deep enough and you find someone like me."],
    chop: ["Timber. It went quietly. Respect.", "A tree down. It had a good run."],
    bones: ["Treat them gently. They were someone.", "Bones. I'm not saying a word. Whose are they?"],
    underground: ["Underground. It feels like coming home.", "Cool, dark and quiet. Where's the downside?"],
    mountain: ["High up. The wind whistles through me.", "Mind the edge. I'd survive the fall. You wouldn't."],
    sea: ["The sea. I'd sink like a stone. Happily.", "Waves. Everything down there ends up like me eventually."],
    hollow: ["Something here wants me back.", "I don't like this. And I like graveyards."],
    swamp: ["A bog. It keeps bodies for centuries. Professional respect."],
    desert: ["Dry heat. Lovely for the joints."],
    lava: ["Lava. Even bones have limits."],
    mixture: ["That went straight to the marrow."],
    outfit: ["New clothes. Finally something to hang on these shoulders.", "Do I look less dead? Don't answer that."],
    friend_near: ["Another Friend. Don't mention my ribs.", "Company. Act alive."],
    village: ["A village. Smile at them. I've only got teeth."],
    ruin: ["Ruins. Someone's old house. Someone's old everything."],
    water: ["Water. I'd see the bottom. Then I'd stay there."],
    full_pack: ["The pack's full. I'd carry something, but I'm mostly gaps."],
    coins: ["Coins. You can't take them with you. I checked."],
    shop: ["A shop. Buy something that lasts. Like me."],
    bank: ["The bank. A vault. My kind of building."],
    pet: ["A pet. Keep it away from my shins."],
    idle: ["…", "Still here. Still dead. Still here.", "I tried to remember my name. I got as far as the bones.", "If I had a stomach, it would be rumbling.", "Lovely day for a funeral. Anyone's.", "My elbow's on backwards again. Hold on."],
  },
  // ---------- 1 Mask: says little, watches everything ----------
  {
    region: ["{name}. Keep your face still.", "{name}. Nobody here knows us. Good.", "{name}. Count the doors.", "{name}. They're already watching."],
    revisit: ["{name}. They remember the mask, not the face.", "Back in {name}. The same eyes on us."],
    night: ["Night. Faces rest.", "Dark. Now we can talk."],
    rain: ["Rain. Good for hiding tears. Not mine.", "…rain."],
    storm: ["Thunder. Everyone looks up. Not us.", "A storm covers footsteps."],
    fog: ["Fog. Everyone's masked now."],
    dawn: ["Light. Faces on."],
    snow: ["Snow. It shows our tracks. Careful."],
    creature: ["That {name}. Don't let it read you.", "{name}. It hasn't decided about us yet.", "{name}. Hold still. Let it pass."],
    creature_again: ["{name}. We've met.", "That {name} again. The same face."],
    dragon: ["A dragon. Don't meet its eyes.", "Dragon. It sees through everything. Even this."],
    dragon_again: ["Another one. It hasn't forgotten us.", "Dragon. Stay masked."],
    undead: ["Faces gone. Still walking.", "They lost more than a mask."],
    grave: ["Under every stone, a face nobody sees.", "Leave them their quiet."],
    altar: ["An altar. Masks come off here.", "Kneel. Keep the mask on."],
    statue: ["A face carved to last. Brave.", "He shows his face. Bold."],
    fight: ["Now.", "Watch the hands, not the eyes.", "Quietly. Then quickly."],
    hurt: ["A crack. Nothing more.", "…it didn't see that coming either.", "Bleed later."],
    rare: ["Ours. Say nothing.", "Hide it well."],
    quest: ["Done. Let them guess who.", "Finished. No names."],
    boss: ["Down. It never saw our face.", "It's over. Walk away slowly."],
    death: ["The mask slipped.", "Seen. Once. Never again."],
    mount: ["Higher. Harder to read.", "Ride. Faces blur at speed."],
    fellowship: ["A fellowship. Many masks.", "Fellows. Trust them slowly."],
    mastery: ["Ninety-nine. Wear it quietly.", "Ninety-nine. They'll ask how. Don't tell them."],
    levelup: ["Stronger. Show nothing.", "A level. Keep it behind the mask."],
    tired: ["Walk. Running draws eyes.", "Slow. Quiet."],
    mine: ["Stone keeps its secrets. So do we.", "Dig. Don't speak."],
    chop: ["The trees hear everything.", "Chop. Count the strokes. Silently."],
    bones: ["Bones. The face is always the first to go.", "Someone's last secret."],
    underground: ["No eyes down here.", "Dark. Honest dark."],
    mountain: ["High. Out of sight.", "Wind. It carries words away."],
    sea: ["The sea keeps no faces.", "Water. Don't look at your reflection."],
    hollow: ["It's searching for a face to wear.", "Don't answer it. Don't look."],
    swamp: ["The bog keeps what it's given."],
    desert: ["Sand wipes out every track."],
    lava: ["Fire. Masks melt."],
    mixture: ["Many faces. All of them mine."],
    outfit: ["A new disguise. Good.", "Better. Harder to place."],
    friend_near: ["One of us. It knows.", "A face I know. Nod. That's enough."],
    village: ["People. Smile with the mask."],
    ruin: ["Whoever lived here left without their faces."],
    water: ["Still water. A mirror. Look away."],
    full_pack: ["Full. Choose what to forget."],
    coins: ["Coins. Quiet ones spend best."],
    shop: ["A shop. Pay. Don't chat."],
    bank: ["The bank. Secrets behind bars."],
    pet: ["It sees the real face. Clever thing."],
    idle: ["…", "…", "Hm.", "Someone's always watching.", "Listen. Not with your ears.", "…no. Nothing."],
  },
  // ---------- 2 Family: warm, fussing, always thinking of home ----------
  {
    region: ["{name}! Doesn't it look lovely?", "{name}. Let's find somewhere for a cup of tea.", "{name}! Did we lock the bank?", "{name}. Wave at people. Be friendly."],
    revisit: ["{name} again! Like coming home.", "Back in {name}. I hope someone saved us a seat."],
    night: ["Getting dark. Have you eaten?", "Night already. Somebody's waiting up for us."],
    rain: ["Rain! Hood up. Hood UP.", "You'll catch your death. Let's find a roof."],
    storm: ["Thunder! Stay away from the tall trees, love.", "A storm. Count the seconds with me."],
    fog: ["Fog. Stay where I can see you."],
    dawn: ["Good morning! Did you sleep? You didn't sleep."],
    snow: ["Snow! Where's your scarf? I packed you a scarf."],
    creature: ["That {name}! Careful, love.", "{name}. Stay close to me.", "{name}! Don't you dare try to pet it."],
    creature_again: ["Another {name}. We've managed worse.", "{name} again. They're like the in-laws."],
    dragon: ["A DRAGON. Hold my hand. Tighter.", "Oh my days. A dragon. Be polite."],
    dragon_again: ["Another dragon. Deep breaths.", "Dragon again. Wait till I tell everyone at home."],
    undead: ["Oh, those poor things. They were somebody's.", "They just want to go home. Don't we all."],
    grave: ["Somebody's missed. Say something kind.", "A grave. Some flowers would be nice."],
    altar: ["Say a little something for the folks at home.", "An altar. Light a candle for Grandma."],
    statue: ["He's got a kind face. Like my uncle.", "The Old Friend. That beard means well."],
    fight: ["Be careful! I mean it!", "Not the face! Never the face!", "Watch your back! And your front!"],
    hurt: ["Oh! Sit down a minute. No? Then be careful!", "Are you all right? You're not all right.", "That's it, we're getting you a plaster."],
    rare: ["Look what we found! That's going on the mantelpiece.", "Treasure! Wait till Grandma hears."],
    quest: ["We did it. I'm so proud of you.", "Finished! Tell everyone. Tell the baker."],
    boss: ["It's over. Come here. Group hug.", "We did that. Us! I need a sit-down."],
    death: ["We're all right. We're all right. Aren't we?", "Never do that again. Promise me."],
    mount: ["Hello, gorgeous. Who's a good horse?", "It needs a name. And an apple. And a blanket."],
    fellowship: ["A fellowship! We'll have them all round for supper.", "New friends! Best behaviour, please."],
    mastery: ["Ninety-nine! I'm writing to everyone.", "Ninety-nine! I knew you could. I always knew."],
    levelup: ["A level! Clever thing.", "Look at you, all grown up."],
    tired: ["Let's walk. There's never any rush.", "Have a breather. Have a biscuit."],
    mine: ["Mind your fingers on that pick.", "Careful. Rocks are heavier than they look."],
    chop: ["Firewood for the winter. Good thinking.", "Shout timber! Somebody might be under it."],
    bones: ["Poor dear. Wrap them up nicely.", "Bones. Handle them with care, they were somebody's."],
    underground: ["It's damp. Don't catch a chill.", "Mind the steps down here. Mind ALL the steps."],
    mountain: ["What a view! Don't stand near the edge.", "So high! Take it slowly."],
    sea: ["Smell that air! We should have brought sandwiches.", "The seaside! Don't go out too far."],
    hollow: ["I don't like it here. Let's not stay long.", "Stay close. Closer than that."],
    swamp: ["Boots on. It's ever so boggy."],
    desert: ["Hat on. Water. Did we bring water?"],
    lava: ["Back from the edge! Honestly!"],
    mixture: ["Ooh, that's warming. Like soup for the soul."],
    outfit: ["Very smart. Turn round. Lovely.", "Oh, that suits you. Mostly."],
    friend_near: ["Another Friend! Say hello nicely.", "Company! Be friendly."],
    village: ["A village! Let's see who's about."],
    ruin: ["Ruins. Somebody called this home once."],
    water: ["Not too close to the water, love."],
    full_pack: ["The pack's full. We should bank some. We should always bank some."],
    coins: ["Coins! Put them somewhere safe."],
    shop: ["A shop. Don't spend it all at once."],
    bank: ["The bank. Good. Put a little aside."],
    pet: ["Oh, hello, little one! Who's a good one?"],
    idle: ["Hmm.", "Are you hungry? You look hungry.", "We should write home.", "I wonder what the others are doing.", "Have you got everything? Check again.", "I like it here. Do you like it here?"],
  },
  // ---------- 3 Cellular: curious, scientific, counts everything ----------
  {
    region: ["{name}. New samples to take.", "{name}. Different soil. Fascinating.", "{name}. Note the plants. Note the animals.", "{name}. Unrecorded. Until now."],
    revisit: ["{name}. A repeat observation. Same results.", "Back in {name}. Let's see what's changed."],
    night: ["Light levels falling. Noted.", "Night. The nocturnal species come out."],
    rain: ["Rain. The fungi will be thrilled.", "Rain. Ideal conditions. For moss."],
    storm: ["Electrical discharge. Fascinating. Stay away from it.", "Lightning. I'd love a sample. I'd hate a sample."],
    fog: ["Poor visibility. Rely on the other senses."],
    dawn: ["Morning. The plants are waking up."],
    snow: ["Snow. Every flake different. I've checked twelve."],
    creature: ["{name}. Observe the gait.", "Specimen: {name}. Hostile, probably.", "{name}. I'd love a closer look. From here."],
    creature_again: ["{name}, specimen {n}. The sample's growing.", "Another {name}. The population is healthy."],
    dragon: ["A dragon. I need a much bigger notebook.", "Dragon. Cold-blooded? It is not cold-blooded."],
    dragon_again: ["Another dragon. A breeding population. Concerning.", "Dragon number two. Or ten. I've lost count."],
    undead: ["Dead tissue, still moving. I have so many questions.", "Reanimated. Against every rule I know."],
    grave: ["Decomposition. Nature's own apothecary.", "The soil's rich here. I won't ask why."],
    altar: ["Strange residue. Don't touch it. I'm touching it.", "An altar. Something reacts here."],
    statue: ["Lichen on the beard. Centuries old.", "The Old Friend. The erosion says he's older than the town."],
    fight: ["Observe the pattern. Then strike.", "Its left side's weaker. Probably.", "Hypothesis: we win."],
    hurt: ["Tissue damage. Repairable.", "Ow. That's data.", "Pain. Useful. Unpleasant."],
    rare: ["Rare! One in how many? I must know.", "Statistically unlikely. Delightful."],
    quest: ["Hypothesis confirmed.", "Done. Write it up."],
    boss: ["Apex specimen, down.", "Fascinating anatomy. Now it's an exhibit."],
    death: ["Cell death. Temporary. Interesting.", "Expired. Restarted. I must look into that."],
    mount: ["Four legs. Efficient locomotion.", "A quadruped. Faster. Smellier."],
    fellowship: ["A colony! Group behaviour is beneficial.", "Fellows. More hands for the samples."],
    mastery: ["Ninety-nine. The curve finally flattens.", "Ninety-nine. The maximum observed."],
    levelup: ["Growth. As predicted.", "A level. The data agrees."],
    tired: ["Energy reserves low. Walk.", "Fatigue. Rest is recommended."],
    mine: ["Note the layers in the rock.", "Good ore. The vein runs that way."],
    chop: ["Count the rings. An old tree.", "Wood fibre. Lots of it."],
    bones: ["Bones. Excellent specimens.", "Calcium. Somebody's."],
    underground: ["Humid. Things grow here.", "Underground. Note the moulds."],
    mountain: ["Thin air. Tough plants.", "Altitude. Fewer specimens. Better views."],
    sea: ["Salt water. Teeming. Pearlweed, perhaps.", "The sea. Everything in it is wet and alive."],
    hollow: ["Nothing grows here. Nothing should be able to.", "No readings at all. That's the worrying part."],
    swamp: ["Fungi! Everywhere! Don't lick anything."],
    desert: ["Arid. Succulents. Sunthorn, ideally."],
    lava: ["Some creatures would love it here. I would not."],
    mixture: ["Division. I can feel myself splitting."],
    outfit: ["Protective, presumably.", "Fibres. Adequate."],
    friend_near: ["Another of us. Compare notes.", "A second specimen. Wave."],
    village: ["A settlement. Observe the population."],
    ruin: ["Ruins. Lovely moss."],
    water: ["Water. Something's swimming. Several somethings."],
    full_pack: ["Capacity reached. Sort the samples."],
    coins: ["Currency. Count it twice."],
    shop: ["Trade. Compare prices."],
    bank: ["Storage. Catalogue everything."],
    pet: ["A companion organism. Feed it regularly."],
    idle: ["Hmm.", "Interesting.", "Noted.", "I counted the trees. I'll need to recount.", "Everything here is alive. Even the rocks, slowly.", "What would happen if we planted a sigil?"],
  },
  // ---------- 4 Asymmetry: lopsided, odd, funny by accident ----------
  {
    region: ["{name}. It's crooked. I like it already.", "{name}. The left half's nicer.", "{name}. Nothing lines up. Home!", "{name}. It leans. I lean. We'll get on."],
    revisit: ["{name} again. Or the first time, from the other side.", "Back in {name}. Still a bit wonky. Good."],
    night: ["One eye says night. The other's not sure.", "Dark on the left. Darker on the right."],
    rain: ["Rain on my left. Dry on my right. Typical.", "Rain. It's falling sideways. Finally."],
    storm: ["Lightning! It zigzags. My kind of weather.", "Thunder. It came from both sides. I counted one."],
    fog: ["Fog. I can't tell my sides apart. Same as ever."],
    dawn: ["Morning. The sun came up crooked. I approve."],
    snow: ["Snow. One footprint big, one small. Mine."],
    creature: ["{name}. It's looking at my good side.", "{name}. Lopsided, like me. I like it.", "{name}. Which way is it facing? Which way am I facing?"],
    creature_again: ["{name}. It's leaning. Like me.", "Another {name}. Still crooked."],
    dragon: ["A dragon! Which end is the front?", "Dragon. Both ends look angry."],
    dragon_again: ["Another one. Its wings don't match either.", "Dragon again. I'm warming to them. Literally."],
    undead: ["They're falling apart. Relatable.", "Bits missing. I know the feeling."],
    grave: ["A crooked stone. My kind of stone.", "A grave. Slightly off. Perfect."],
    altar: ["It's off-centre. Holy, but off-centre.", "An altar. I'll kneel on one knee. The good one."],
    statue: ["His beard's longer on the left. Good man.", "The Old Friend. One eye higher than the other. Kindred spirit."],
    fight: ["Hit it on its wonky side.", "Swing! No, the other way!", "Surprise it. I surprise myself every day."],
    hurt: ["Ow. On my good side, too.", "That hit both of my lefts.", "Ouch. Now I'm even. Ugh."],
    rare: ["Treasure! And it's lopsided! Perfect!", "A rare one. Odd. Like us."],
    quest: ["Done! Sideways, but done.", "Finished. Not how anyone planned it. Our way."],
    boss: ["Down! It tipped over. Things do.", "It's down. It went down crooked."],
    death: ["I fell over. More than usual.", "Oops. Back up. Mostly."],
    mount: ["A horse! Its legs are all the same. Weird.", "Ride on. I'll sit sideways."],
    fellowship: ["A fellowship! Do they lean? We'll teach them to lean.", "Fellows! A wonky company. Perfect."],
    mastery: ["Ninety-nine! Which way up does it go?", "Ninety-nine. One side of me is even prouder than the other."],
    levelup: ["A level! One side grew. The other's catching up.", "Up! Sort of diagonally up!"],
    tired: ["Walking. One leg's tireder. Guess which.", "Slow down. I'm going round in circles."],
    mine: ["The lumpy rocks are the good ones. I'd know.", "Hit it off-centre. Trust me."],
    chop: ["Chop it crooked. It'll fall interestingly.", "Timber! Sideways!"],
    bones: ["Bones. None of them match. Lovely.", "Bones. Put them back crooked."],
    underground: ["Underground! Which way's up? Doesn't matter.", "Caves. Wonky walls. I love it."],
    mountain: ["A slope! Finally, the ground agrees with me.", "Uphill. My short leg loves it."],
    sea: ["Waves. They lean too.", "The sea. Tipping everything. My people."],
    hollow: ["This place is perfectly straight. I hate it.", "Something here wants me even. No thank you."],
    swamp: ["A bog. Sinking on one side. As usual."],
    desert: ["Dunes! All lopsided! Heaven."],
    lava: ["Lava. Too hot on both sides."],
    mixture: ["I feel… balanced. Make it stop."],
    outfit: ["One sleeve longer. Perfect fit.", "That suits me. The left of me, anyway."],
    friend_near: ["Another Friend! Lean at them.", "Hello! Tilt your head. That's how we wave."],
    village: ["A village. Every roof's straight. We'll fix that."],
    ruin: ["Ruins. Finally, buildings with personality."],
    water: ["Water. My reflection's the right way round for once."],
    full_pack: ["The pack's full. And heavier on one side."],
    coins: ["Coins! Stack them crooked."],
    shop: ["A shop. Anything mismatched? I'll take it."],
    bank: ["The bank. So many straight lines. Quickly, please."],
    pet: ["A pet! It walks funny. We'll be best friends."],
    idle: ["Hm?", "My left side wants to go left. My right side agrees, which is new.", "Is the world crooked, or is it just me? Both. Both is good.", "I fell over. On purpose. Mostly.", "Which way's up? Diagonal.", "I'm even today. No I'm not."],
  },
  // ---------- 5 Hoverer: restless, curious, always looking further ----------
  {
    region: ["{name}! What's over there?", "{name}! Which way first? Every way first!", "{name}. Let's see all of it. Today.", "{name}! I can see so far from up here."],
    revisit: ["{name} again! Did we check behind the hill last time?", "{name}! There's a bit we missed. There's always a bit we missed."],
    night: ["Night! Everything's an adventure in the dark.", "Stars! Can we go up there? Just to look?"],
    rain: ["Rain! I'll float over the puddles.", "Race the rain to the next roof!"],
    storm: ["Lightning! Did you see that? DID YOU SEE THAT?", "Thunder! Let's get higher. Wait, no."],
    fog: ["Fog! Everything's a surprise now!"],
    dawn: ["Morning! Go, go, go!"],
    snow: ["Snow! Up the mountain! Now!"],
    creature: ["Wait, what's that? {name}!", "{name}! Closer! No? A bit closer?", "{name}! Has anyone seen one up close? Let's be first!"],
    creature_again: ["{name}! Let's go round it. Or over it.", "Another {name}! Different one? Same one? Who cares!"],
    dragon: ["Is that a DRAGON?!", "A dragon! I want to fly like that!"],
    dragon_again: ["Another dragon! Can we keep one?", "Dragon! Race it! No, don't race it."],
    undead: ["They're so slow! We could just float past.", "Skeletons can't jump. Ha!"],
    grave: ["It's quiet here. Let's not stay.", "Graves. Shh. Okay. Now what's over there?"],
    altar: ["Ooh! What does it do? Touch it!", "An altar! Does it grant wishes? Wish for wings!"],
    statue: ["We could get up on his head!", "I can see right up his nose from here."],
    fight: ["Go! Go! Go!", "Hit it from above!", "Quick! Before it gets bored!"],
    hurt: ["Ow! Moving! Moving!", "Ouch! Float faster!", "That stung! Keep going!"],
    rare: ["LOOK! Look at it!", "Shiny! Can we find another one?"],
    quest: ["Done! What's next? What's NEXT?", "Finished! Where to now? Everywhere?"],
    boss: ["We did it! Did you see that?!", "DOWN! It's down! What's the next big thing?"],
    death: ["Okay. Okay. Again!", "Oof. Floating back up."],
    mount: ["Faster! FASTER!", "A horse! It's like floating, but with legs!"],
    fellowship: ["A fellowship! More people to show things to!", "Fellows! Can they keep up?"],
    mastery: ["Ninety-nine! Is there a hundred? Let's find out!", "Ninety-nine! What's past that?"],
    levelup: ["A level! Higher! Higher!", "Up! Up! Up!"],
    tired: ["Okay… maybe we walk. For a bit.", "Puffed. Walking. Boo."],
    mine: ["Rocks. What's behind the rocks?", "Dig faster! There might be a cave!"],
    chop: ["Timber! Did I say that right?", "Can we climb it before it falls?"],
    bones: ["Whose bones? Never mind! Onward!", "Bones! There's a story there, probably. No time!"],
    underground: ["Caves! What's at the end?", "It's dark! I love it! I'm scared! I love it!"],
    mountain: ["The top! Is there a top? Let's find it!", "Higher! Higher!"],
    sea: ["What's across the sea? Let's cross it!", "I can see something past the isles! Maybe!"],
    hollow: ["I don't want to float here.", "Something's pulling me down. I hate down."],
    swamp: ["Squelchy! Good thing I hover."],
    desert: ["What's over the next dune? And the next?"],
    lava: ["Hot! So hot! Pretty, though!"],
    mixture: ["I'm not touching the ground. I'M NOT TOUCHING THE GROUND!"],
    outfit: ["Do I look fast? I feel fast!", "New clothes! Do they flap? Make them flap!"],
    friend_near: ["Hi! HI!", "Another Friend! Race you!"],
    village: ["A village! Roofs to float over!"],
    ruin: ["Ruins! What's inside? What's under? What's on top?"],
    water: ["Water! Skim it! Skim it!"],
    full_pack: ["Full! Drop something! Not that! Not that either!"],
    coins: ["Coins! Spend them on something exciting!"],
    shop: ["A shop! Anything new? Anything NEW?"],
    bank: ["The bank! Quick in, quick out!"],
    pet: ["A pet! Can it fly? Teach it to fly!"],
    idle: ["What's over there?", "Hmm!", "Did you hear that?", "I'm bored. Let's go somewhere. Anywhere.", "What's the furthest we've ever been? Let's beat it.", "Is that a path? That's a path. Let's take it."],
  },
  // ---------- 6 Colossus: slow, blunt, few words ----------
  {
    region: ["{name}. Big.", "{name}. Good ground.", "{name}. Hm.", "{name}. Fine."],
    revisit: ["{name}. Been here.", "{name}. Again. Good."],
    night: ["Dark. Fine.", "Night. Sleep standing."],
    rain: ["Wet.", "Rain. Doesn't matter."],
    storm: ["Loud.", "Thunder. Bigger than me. Just."],
    fog: ["Can't see. Walk anyway."],
    dawn: ["Light. Good."],
    snow: ["Cold. Walk faster."],
    creature: ["{name}. Small.", "{name}. Could fight that.", "{name}. Hm. Fine."],
    creature_again: ["{name}. Again.", "{name}. Still small."],
    dragon: ["Dragon. Big. Good.", "Dragon. Finally. My size."],
    dragon_again: ["Dragon. Again. Good.", "Another big one. Good."],
    undead: ["Thin. Snap easy.", "Bones. Brittle."],
    grave: ["Small hole.", "Grave. Quiet."],
    altar: ["Stone. Good stone.", "Altar. Heavy."],
    statue: ["Beard. Good.", "Stone man. Smaller than me."],
    fight: ["Hit it.", "Hit it harder.", "Mine."],
    hurt: ["Hm.", "Scratch.", "Fine."],
    rare: ["Mine.", "Shiny. Heavy. Good."],
    quest: ["Done.", "Finished. Next."],
    boss: ["Down.", "Was big."],
    death: ["Up.", "Fell. Up again."],
    mount: ["Strong one.", "Horse. Brave horse."],
    fellowship: ["Good. More hands.", "Fellows. Lift things."],
    mastery: ["Ninety-nine. Big number.", "Ninety-nine. Good."],
    levelup: ["Bigger.", "Stronger. Good."],
    tired: ["Walk, then.", "Slow. Fine."],
    mine: ["Good stone.", "Rock. Break it."],
    chop: ["Tree. Push it.", "Big tree. Good."],
    bones: ["Small bones.", "Bones. Carry."],
    underground: ["Low roof. Duck.", "Too small."],
    mountain: ["Mountain. Climb.", "Big. Good."],
    sea: ["Big water.", "Sea. Can't punch it."],
    hollow: ["Cold. Don't like it.", "Empty. Bad empty."],
    swamp: ["Sinking. Walk faster."],
    desert: ["Hot. Heavy sand."],
    lava: ["Hot rock. Don't touch."],
    mixture: ["Bigger. Good."],
    outfit: ["Tight.", "Clothes. Fine."],
    friend_near: ["One of us.", "Friend. Small."],
    village: ["Houses. Small doors."],
    ruin: ["Broken. Was big once."],
    water: ["Water. Walk round."],
    full_pack: ["Full. Carry more. Can't."],
    coins: ["Coins. Heavy. Good."],
    shop: ["Shop. Buy big things."],
    bank: ["Bank. Keep things."],
    pet: ["Small thing. Don't step on it."],
    idle: ["Hm.", "…", "Good.", "Hungry.", "Big rock over there. Good rock.", "Could lift that. Won't."],
  },
  // ---------- 7 Sparkling: bright, delighted, can't contain itself ----------
  {
    region: ["{name}! It's gorgeous!", "{name}! Oh, the light here!", "{name}! Look how it catches the sun!", "{name}! I want to see every bit of it!"],
    revisit: ["{name} again! Still sparkly!", "{name}! I missed the light here!"],
    night: ["Stars! Every single one of them!", "Night! Every lamp's a little jewel!"],
    rain: ["Rain! Everything shines afterwards!", "Raindrops! Thousands of tiny diamonds!"],
    storm: ["LIGHTNING! The sky's showing off!", "Thunder! Applause from the sky!"],
    fog: ["Fog! Soft light everywhere!"],
    dawn: ["Sunrise! Oh, the colours!"],
    snow: ["Snow! It glitters! It GLITTERS!"],
    creature: ["{name}! Isn't it something?", "{name}! Look at its eyes shine!", "{name}! Oh, the colour of it!"],
    creature_again: ["Another {name}! Hello again!", "{name}! Still gorgeous. Still bitey."],
    dragon: ["A dragon! The SCALES!", "Dragon! Imagine the shimmer! From a distance!"],
    dragon_again: ["Another dragon! Each one shinier!", "Dragon! I'll never get used to the sparkle!"],
    undead: ["They've lost their sparkle. Poor things.", "So grey! They need a bit of glitter."],
    grave: ["Some flowers would brighten it.", "Leave something bright. They'd like that."],
    altar: ["Candles! Light them all!", "An altar! Make it glow!"],
    statue: ["He'd look lovely in gold leaf.", "The Old Friend! Polish his beard!"],
    fight: ["Make it dazzling!", "Hit it! Brilliantly!", "Sparkle and strike!"],
    hurt: ["Ow! That'll bruise a pretty colour.", "Ouch! My sparkle!", "That dimmed me. Slightly!"],
    rare: ["It SHINES! We're keeping it!", "Treasure! Real treasure!"],
    quest: ["Done! Fireworks! Where are the fireworks?", "Finished! Confetti, somebody!"],
    boss: ["We did it! I'm glowing!", "Down! And what a show!"],
    death: ["Even stars fall. Up again!", "Oh! That was dark. Back to the light!"],
    mount: ["Ribbons! It needs ribbons!", "A horse! Let's braid its mane!"],
    fellowship: ["A fellowship! We'll glitter together!", "Fellows! A whole constellation!"],
    mastery: ["Ninety-nine! We're brilliant!", "Ninety-nine! Shine, shine, shine!"],
    levelup: ["A level! Sparkle!", "Up! Brighter! Yes!"],
    tired: ["A stroll, then. Sparkle slowly.", "Puffed. Glow gently."],
    mine: ["Gems! Please let there be gems!", "Something glints in there!"],
    chop: ["Look how the chips catch the light!", "Timber! Gracefully!"],
    bones: ["Bones! Polish them up!", "Bones. Pearly white, at least!"],
    underground: ["Dark! I'll light the way!", "Caves! Crystals? Please, crystals!"],
    mountain: ["Snowy peaks! Glittering!", "The view! Catching the light!"],
    sea: ["Look at the light on the water!", "The sea! Sparkling all the way out!"],
    hollow: ["It's so dim here. I don't like dim.", "Even my sparkle's quiet here."],
    swamp: ["Murky! But look, fireflies!"],
    desert: ["Sand! Every grain a glint!"],
    lava: ["LAVA! Oh, the glow! From over here, though!"],
    mixture: ["I'm fizzing! I'm actually fizzing!"],
    outfit: ["Oh, that's fabulous!", "Darling, the colour on you!"],
    friend_near: ["Another Friend! Twinkle at them!", "Company! Shine together!"],
    village: ["A village! Window boxes! Lanterns!"],
    ruin: ["Ruins! Imagine them all lit up!"],
    water: ["Water! Look at it shimmer!"],
    full_pack: ["Full! Of lovely things!"],
    coins: ["Coins! Gold! Shiny gold!"],
    shop: ["A shop! Anything with a shimmer, please!"],
    bank: ["The bank! Hello, my treasures!"],
    pet: ["A pet! Can it wear a bow?"],
    idle: ["Ooh!", "Pretty.", "Everything's so pretty, isn't it?", "I think I'm glowing a bit. Am I glowing?", "Look at the light. Just look at it.", "Oh! A butterfly!"],
  },
  // ---------- 8 Hollow: quiet, strange, knows things it shouldn't ----------
  {
    region: ["{name}. It's thinner here.", "{name}. Something underneath remembers us.", "{name}. The ground hums a different note.", "{name}. Someone was here before anyone."],
    revisit: ["{name}. The echo's still here.", "{name} again. It remembers us."],
    night: ["The dark's closer. Good.", "Night. The thin hours."],
    rain: ["It falls straight through me.", "Rain. It doesn't touch what I am."],
    storm: ["Lightning. Something flinches, far below.", "Thunder. Something down there answered."],
    fog: ["Fog. The world's not sure it's there. I know the feeling."],
    dawn: ["Light. It pushes."],
    snow: ["Snow. Cold like home. Almost."],
    creature: ["{name}. It can't see what I am.", "{name}. It smells the cold on me.", "{name}. It knows something's wrong. It's me."],
    creature_again: ["{name}. It still can't tell.", "Another {name}. They never learn what I am."],
    dragon: ["A dragon. Older than me. Just.", "Dragon. It knows. Look at it."],
    dragon_again: ["Another. They don't like what I am.", "Dragon. It looks away. Wise."],
    undead: ["They almost got there.", "Half-made. Poor things."],
    grave: ["Not empty. They never are.", "Something's listening under it."],
    altar: ["It hums. Can't you hear it?", "An altar. It's connected. To what, I won't say."],
    statue: ["He's not looking at you. He's looking at me.", "The Old Friend. He knew. I think he knew."],
    fight: ["Let it come.", "Through it, not round it.", "It's afraid. Good."],
    hurt: ["It went through. Mostly.", "Another hole. I collect them.", "That's not where I keep anything."],
    rare: ["This was lost. Now it isn't.", "Found. It was waiting for us."],
    quest: ["Finished. Something noticed.", "Done. The echo changed."],
    boss: ["It's gone where I came from.", "Down. I know where it went."],
    death: ["Not gone. Never gone.", "Back. I always come back."],
    mount: ["It feels the cold in me. Brave thing.", "It shivers. It carries me anyway."],
    fellowship: ["A fellowship. They don't know what they've let in.", "Fellows. They'll learn."],
    mastery: ["Ninety-nine. The edge of something.", "Ninety-nine. It's thin, up here."],
    levelup: ["Deeper.", "A level. The hollow widens."],
    tired: ["Walk. The ground doesn't mind.", "Slow. The dark can wait."],
    mine: ["There's a hollow under the hollow.", "Dig carefully. Something's down there."],
    chop: ["It screams, a little. You can't hear it.", "The tree remembers being planted."],
    bones: ["They want to go somewhere.", "Bones. The shape of what's missing."],
    underground: ["Closer to home.", "Deeper. Yes.", "Down here, the hum is a voice."],
    mountain: ["Thin air. Thinner me.", "High. Far from the hum."],
    sea: ["Nothing of mine out there.", "The sea doesn't know me. Good."],
    hollow: ["I'm home. We shouldn't be.", "It knows me. Keep walking.", "The crown's near. I can feel it weighing nothing."],
    swamp: ["Still water. Deep. Something looks back."],
    desert: ["Dry. The hollow hates dry."],
    lava: ["Fire. The opposite of me. Keep it there."],
    mixture: ["The shadows lean in. Let them."],
    outfit: ["A shape to hold onto.", "Clothes. Something to be seen in."],
    friend_near: ["One of us. Does it know?", "A Friend. It feels the cold, and stays. Good."],
    village: ["People. Warm. They look at me twice."],
    ruin: ["Whoever built this went where I'm from."],
    water: ["Water. No reflection. Don't look."],
    full_pack: ["Full. Let something go. I know how."],
    coins: ["Coins. Weight. I have none of my own."],
    shop: ["A shop. They'll take my coin. Not my hand."],
    bank: ["The bank. Kept things wait."],
    pet: ["It isn't afraid of me. Why isn't it afraid?"],
    idle: ["…", "Listen.", "The hum changed. Did you feel it?", "Something under us turned over.", "I was somewhere else a moment ago. I'm back.", "Don't look at the shadows. They look back."],
  },
];

/** A Friend of no family we know: plain words for everything. */
export const PLAIN: Voice = {
  region: ["{name}."], revisit: ["{name} again."], night: ["Night."], rain: ["Rain."], storm: ["A storm."], fog: ["Fog."], dawn: ["Morning."], snow: ["Snow."],
  creature: ["{name}."], creature_again: ["Another {name}."], dragon: ["A dragon!"], dragon_again: ["Another dragon."], undead: ["The dead, walking."], grave: ["A grave."], altar: ["An altar."], statue: ["A statue."],
  fight: ["Here we go."], hurt: ["Ow."], rare: ["Look at that."], quest: ["Done."], boss: ["It's down."], death: ["…"], mount: ["Up we get."], fellowship: ["A fellowship."], mastery: ["Ninety-nine."], levelup: ["A level."],
  tired: ["Let's walk."], mine: ["Rock."], chop: ["Wood."], bones: ["Bones."], underground: ["Dark."], mountain: ["High."], sea: ["The sea."], hollow: ["…"], swamp: ["A bog."], desert: ["Sand."], lava: ["Lava."],
  mixture: ["Hm."], outfit: ["Hm."], friend_near: ["Hello."], village: ["A village."], ruin: ["Ruins."], water: ["Water."], full_pack: ["Full."], coins: ["Coins."], shop: ["A shop."], bank: ["The bank."], pet: ["A pet."], idle: ["Hmm."],
};

/** Working a skill: what anyone might say, and what each family says (heard twice as often). */
export const SKILL_LINES: Partial<Record<Skill, { shared: readonly string[]; family: Partial<Record<number, readonly string[]>> }>> = {
  woodcutting: { shared: ["Mind the splinters.", "This one's stubborn.", "Logs for the fire, or for the bank?"], family: { 0: ["The tree's dead. It just doesn't know yet."], 2: ["Wrap up. There's a draught through these trees."], 5: ["Climb it first! No? Fine. Chop."], 6: ["Push it. Faster."], 7: ["The chips catch the light!"], 8: ["It remembers being an acorn."] } },
  mining: { shared: ["There's a vein in that.", "Chip, chip, chip.", "Good ore, maybe."], family: { 0: ["Rock. Harder than bone. Just."], 3: ["Note the layers."], 4: ["The lumpy ones are the good ones."], 6: ["Good stone."], 7: ["Gems. Please. Gems."], 8: ["Something's under the rock. Under everything."] } },
  fishing: { shared: ["Patience.", "Something's nibbling.", "The water's calm. Suspiciously calm."], family: { 0: ["Fish have bones too. I feel for them."], 2: ["Fresh fish for supper. Lovely."], 3: ["Note the species."], 5: ["This is slow. This is SO slow."], 6: ["Big fish. Good."], 7: ["The scales! Oh, the scales!"], 8: ["Something under the water is fishing too."] } },
  cooking: { shared: ["Don't burn it.", "Smells good. Mostly.", "Turn it. Turn it now."], family: { 0: ["Cook it through. You've got a stomach. I haven't."], 2: ["A pinch of salt. Another. There."], 4: ["Burnt on one side. Perfect."], 6: ["Eat. Big."], 7: ["Golden! Look at it!"], 8: ["Fire. The one thing I keep my distance from."] } },
  firemaking: { shared: ["There it goes.", "Warm hands.", "Keep it fed."], family: { 0: ["Bones don't burn well. Let's not find out."], 2: ["Come and warm your feet."], 5: ["Sparks! Up they go!"], 7: ["Dancing light! Oh!"], 8: ["It flinches from me. Good."] } },
  smithing: { shared: ["Hammer it, don't tap it.", "Red hot. Mind it.", "Another bar, another blade."], family: { 0: ["Metal. Harder than bone. Everything is."], 3: ["Note the temper."], 4: ["Hammer it crooked. It'll fly truer."], 6: ["Good. Heavy. Mine."], 7: ["A fountain of sparks!"], 8: ["The metal remembers the fire. So do I."] } },
  crafting: { shared: ["Neat stitches.", "Nearly there.", "Careful with the needle."], family: { 0: ["Leather. I'd offer my own skin, but."], 2: ["A good tight stitch. Grandma would approve."], 4: ["An uneven hem. Keep it."], 7: ["Add a bead. Add ten."], 8: ["Thread holds a shape together. I envy it."] } },
  fletching: { shared: ["Straight shafts.", "Feathers, then heads.", "That'll fly."], family: { 0: ["Arrows. Pointy bones, really."], 5: ["Make them fast. Faster than me."], 6: ["Big arrows. Good."], 7: ["Gold feathers. Trust me."] } },
  magic: { shared: ["The sigils are humming.", "Steady. Focus.", "The air's thick with it."], family: { 1: ["Magic. The best mask there is."], 3: ["Observe the sigil. Then spend it."], 7: ["Sparks! Real ones!"], 8: ["Spells keep their sigils for me. I don't ask why."] } },
  prayer: { shared: ["Light a candle.", "Say the words.", "The altar's warm."], family: { 0: ["Bones on the altar. Mine, someday. Not today."], 2: ["Say one for Grandma."], 7: ["Light all the candles!"], 8: ["The altar knows me. It doesn't mind."] } },
  apothecary: { shared: ["Clean it first.", "Grind it, don't bash it.", "That'll brew."], family: { 0: ["Poison. Keep it off me. I think I'm immune."], 2: ["Basically soup. Dangerous soup."], 3: ["Observe the reaction."], 4: ["Stir it the wrong way. Trust me."], 5: ["Does it fizz? Make it fizz!"], 6: ["Drink. Strong."], 7: ["Bottle that colour!"], 8: ["Something in that vial is awake."] } },
  thieving: { shared: ["Quietly.", "Soft hands.", "Don't get caught."], family: { 1: ["Light fingers. Lighter face."], 5: ["Grab it and float!"], 6: ["Sneaking. Hard. Big feet."], 8: ["Nobody sees me. Nobody could."] } },
  agility: { shared: ["Mind the gap.", "Don't look down.", "Breathe."], family: { 0: ["If I come apart, pick me up."], 4: ["Land on the good foot."], 5: ["Jump! Float! Jump!"], 6: ["Too small. Jump anyway."], 7: ["Leap! Gracefully! Sort of!"] } },
  slayer: { shared: ["On task.", "Count them.", "The Warden will want to know."], family: { 0: ["More bones for the world. I approve."], 6: ["Big things. Good."], 8: ["They go where I'm from. I'll show them the way."] } },
  hitpoints: { shared: ["Still standing.", "Breathe."], family: {} },
  presence: { shared: ["People remember that.", "They'll talk about us."], family: { 1: ["Known. Even behind a mask."], 7: ["They'll remember the sparkle!"] } },
  sigilcraft: { shared: ["Press it in.", "Stone into sigil."], family: { 3: ["The stone changes state. Note it."], 8: ["The altar takes the stone. It takes other things too."] } },
  ranged: { shared: ["Steady aim.", "Loose."], family: { 5: ["From above! Shoot from above!"], 6: ["Small arrows. Hit anyway."] } },
  attack: { shared: ["Again.", "Strike true."], family: {} },
  strength: { shared: ["Harder.", "Put your back into it."], family: { 6: ["Hit. Good."] } },
  defence: { shared: ["Shield up.", "Hold."], family: {} },
};

/** Talk for no reason at all, by family. */
export const CHATTER: readonly (readonly string[])[] = [
  ["I wonder who I was. I hope they wouldn't mind.", "Everyone's a skeleton underneath. I'm just honest about it.", "My knees click. I don't have knees.", "You go on ahead. I'll haunt the back.", "People stare. Let them. Good bones.", "Do you ever think about the bones you're carrying around? I do.", "I can whistle through my ribs. Don't ask me to."],
  ["…", "Who's behind your face? Who's behind that one?", "They think they know me. They know the mask.", "I wore a different face yesterday. You didn't notice.", "Say less.", "Everyone wears one. Mine's just honest about it.", "…I like this place."],
  ["Did you remember to eat?", "We should visit Grandma. We don't have a Grandma. We should find one.", "Is it bedtime? It's nearly bedtime.", "I packed a spare scarf. You'll thank me.", "Nice people here. Mostly.", "Write home. I'll tell you what to say.", "What's for supper?"],
  ["I counted the stars. I lost count. Starting again.", "Everything's made of smaller things. Even that.", "Hypothesis: it'll rain. Evidence: it's raining.", "The birds here sing a tone lower. Noted.", "What would happen if we planted a coin?", "The soil here is wrong. Interestingly wrong.", "I've been dividing. Don't look."],
  ["My left side wants to go left. My right side agrees, which is new.", "Everything leans. Trees, houses, me. Especially me.", "Is the world crooked, or is it just me? Both. Both is fine.", "I fell over. I meant to.", "Which way's up? Trick question. Diagonal.", "Nothing lines up. Beautiful.", "I'm even today. No I'm not."],
  ["What's over there? And there? And THERE?", "Everything's better from higher up.", "I can see the sea from here. I can't. I want to.", "Race you to that tree! You lost. Again!", "Let's go somewhere we've never been. Now!", "I'm bored. Say something. Anything!", "Can we fly today? Jump. Try!"],
  ["Hm.", "Hungry.", "Big sky.", "Could lift that house. Won't.", "Good rock there.", "Something small ran past. Fine.", "Walk. Walking is good."],
  ["I think I'm glowing a bit. Am I glowing?", "Look at the light! Just look!", "Everything's pretty if you squint. Squint!", "I'd like a hat with a jewel on it. Two jewels.", "Oh! A butterfly! Oh! Another one!", "Shine on, everything.", "Twinkle. That's all I'm saying. Twinkle."],
  ["The hum changed.", "Something under us just turned over.", "I was elsewhere for a moment. I'm back.", "Don't look at the shadows. They look back.", "I know what's under this field. I won't say.", "Cold. Always a little cold. It's fine.", "They're nearly ready to come back. Not yet."],
];

export const SHARED_CHATTER: readonly string[] = ["Nice day for it.", "Long way from home.", "Did you hear that?", "Look.", "Hmm.", "What now?", "Whoa.", "Interesting.", "I don't like that.", "…", "Onwards."];
